"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import importlib
sys_conf = importlib.import_module("enviroments." + os.getenv('APP_ENV', 'local'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l@q$eiby-oc$pl1@3x*ll^6e!&kb+4!ee7$r$ug3renemj1)1*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = sys_conf.DEBUG

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'my_app'
]

REST_FRAMEWORK = sys_conf.REST_FRAMEWORK

MIDDLEWARE = sys_conf.MIDDLEWARE

ROOT_URLCONF = 'my_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': os.getenv('MYSQL_DATABASE_DB', sys_conf.NAME),
        'USER': os.getenv('MYSQL_DATABASE_USER', sys_conf.USER),
        'PASSWORD': os.getenv('MYSQL_DATABASE_PASSWORD', sys_conf.PASSWORD),
        'HOST': os.getenv('MYSQL_DATABASE_HOST', sys_conf.HOST),
        'PORT': os.getenv('MYSQL_DATABASE_PORT', sys_conf.PORT),
    }
}

REDIS_HOST = str(os.getenv("CACHE_DB_HOST", sys_conf.REDIS_HOST))
REDIS_PORT = str(os.getenv("CACHE_DB_POST", sys_conf.REDIS_PORT))
REDIS_DB = str(os.getenv("CACHE_DB_NAME", sys_conf.REDIS_DB))

REDIS_CONNECTION_CUSTOM = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/' + REDIS_DB

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_CONNECTION_CUSTOM,
        'KEY_PREFIX': 'session',
        # redis://username:password@127.0.0.1:6379
    }
}

SESSION_CACHE_ALIAS = 'default'

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

CELERY_BROKER_URL = REDIS_CONNECTION_CUSTOM

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
